language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "python setup.py develop"
  - "pip install ."
  - "pip install pytest coveralls"
script:
  coverage run --source=smalluuid runtests.py
after_success:
  coveralls
